In [1]:
import pandas as pd
import os
import matplotlib.pyplot as plt
from matplotlib import cm
import seaborn as sns
import seaborn.objects as so
import numpy as np
import gc
from datetime import datetime, timezone

from scipy import stats

In [2]:
os.listdir("/Users/25298423/Downloads/RockyShoreMacroalgae_unzipped")

['EPA.xml',
 'RockyShoreMacroalgae.csv',
 'RockyShoreMacroalgae.txt',
 'RockyShoreMacroalgae.xml']

In [3]:
rocky_algae = pd.read_csv("/Users/25298423/Downloads/RockyShoreMacroalgae_unzipped/RockyShoreMacroalgae.csv")
rocky_algae

,RecordKey,SurveyKey,SampleKey,StartDate,EndDate,DateType,Date,TaxonVersionKey,TaxonName,GridReference,...,North,Projection,Precision,SiteKey,SiteName,Recorder,Determiner,ZeroAbundance,UnderValidation,ImagePath
0,2109.0,NaN,NaN,12/5/2009,12/5/2009,D,12/5/2009,NHMSYS0021058637,Ascophyllum nodosum,NaN,...,51.460563,WGS84,100,NaN,Galley Cove,"Robert Wilkes, EPA",Robert Wilkes,False,False,NaN
1,2111.0,NaN,NaN,12/5/2009,12/5/2009,D,12/5/2009,NHMSYS0021058656,Bifurcaria bifurcata,NaN,...,51.460563,WGS84,100,NaN,Galley Cove,"Robert Wilkes, EPA",Robert Wilkes,False,False,NaN
2,2114.0,NaN,NaN,12/5/2009,12/5/2009,D,12/5/2009,NHMSYS0021060171,Callophyllis laciniata,NaN,...,51.460563,WGS84,100,NaN,Galley Cove,"Robert Wilkes, EPA",Robert Wilkes,False,False,NaN
3,2115.0,NaN,NaN,12/5/2009,12/5/2009,D,12/5/2009,NHMSYS0021060119,Catenella caespitosa,NaN,...,51.460563,WGS84,100,NaN,Galley Cove,"Robert Wilkes, EPA",Robert Wilkes,False,False,NaN
4,2116.0,NaN,NaN,12/5/2009,12/5/2009,D,12/5/2009,NHMSYS0021059800,Ceramium shuttleworthianum,NaN,...,51.460563,WGS84,100,NaN,Galley Cove,"Robert Wilkes, EPA",Robert Wilkes,False,False,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10809,2532.0,NaN,NaN,16/09/2009,16/09/2009,D,16/09/2009,NHMSYS0021060033,Plumaria plumosa,NaN,...,55.264523,WGS84,100,NaN,Lenan Head,"Robert Wilkes, EPA",Robert Wilkes,False,False,NaN
10810,2533.0,NaN,NaN,16/09/2009,16/09/2009,D,16/09/2009,NHMSYS0021060205,Polyides rotunda,NaN,...,55.264523,WGS84,100,NaN,Lenan Head,"Robert Wilkes, EPA",Robert Wilkes,False,False,NaN
10811,2536.0,NaN,NaN,16/09/2009,16/09/2009,D,16/09/2009,NHMSYS0021060280,Rhodothamniella floridula,NaN,...,55.264523,WGS84,100,NaN,Lenan Head,"Robert Wilkes, EPA",Robert Wilkes,False,False,NaN
10812,2537.0,NaN,NaN,16/09/2009,16/09/2009,D,16/09/2009,NHMSYS0000567730,Scytosiphon lomentaria nom. cons.,NaN,...,55.264523,WGS84,100,NaN,Lenan Head,"Robert Wilkes, EPA",Robert Wilkes,False,False,NaN
10813,2538.0,NaN,NaN,16/09/2009,16/09/2009,D,16/09/2009,NHMSYS0021381089,Ulva fenestrata,NaN,...,55.264523,WGS84,100,NaN,Lenan Head,"Robert Wilkes, EPA",Robert Wilkes,False,False,NaN

In [4]:
rocky_algae.columns

Index(['RecordKey', 'SurveyKey', 'SampleKey', 'StartDate', 'EndDate',
       'DateType', 'Date', 'TaxonVersionKey', 'TaxonName', 'GridReference',
       'East', 'North', 'Projection', 'Precision', 'SiteKey', 'SiteName',
       'Recorder', 'Determiner', 'ZeroAbundance', 'UnderValidation',
       'ImagePath'],
      dtype='object')

In [5]:
rocky_algae.describe()

,RecordKey,SurveyKey,SampleKey,GridReference,East,North,Precision,SiteKey,ImagePath
count,1.081400e+04,0.0,0.0,0.0,10814.000000,10814.000000,10814.0,0.0,0.0
mean,7.337826e+16,NaN,NaN,NaN,-8.782179,52.968910,100.0,NaN,NaN
std,4.378293e+16,NaN,NaN,NaN,1.251751,1.146388,0.0,NaN,NaN
min,2.000000e+00,NaN,NaN,NaN,-10.376206,51.460563,100.0,NaN,NaN
25%,3.416250e+03,NaN,NaN,NaN,-9.800819,51.811778,100.0,NaN,NaN
50%,9.950000e+16,NaN,NaN,NaN,-9.065290,53.244986,100.0,NaN,NaN
75%,9.950000e+16,NaN,NaN,NaN,-8.239798,54.243350,100.0,NaN,NaN
max,9.950000e+16,NaN,NaN,NaN,-6.013210,55.264523,100.0,NaN,NaN

In [6]:
rocky_algae.drop(columns=['SurveyKey','SampleKey','GridReference','SiteKey','ImagePath'], inplace=True)
rocky_algae

,RecordKey,StartDate,EndDate,DateType,Date,TaxonVersionKey,TaxonName,East,North,Projection,Precision,SiteName,Recorder,Determiner,ZeroAbundance,UnderValidation
0,2109.0,12/5/2009,12/5/2009,D,12/5/2009,NHMSYS0021058637,Ascophyllum nodosum,-9.740788,51.460563,WGS84,100,Galley Cove,"Robert Wilkes, EPA",Robert Wilkes,False,False
1,2111.0,12/5/2009,12/5/2009,D,12/5/2009,NHMSYS0021058656,Bifurcaria bifurcata,-9.740788,51.460563,WGS84,100,Galley Cove,"Robert Wilkes, EPA",Robert Wilkes,False,False
2,2114.0,12/5/2009,12/5/2009,D,12/5/2009,NHMSYS0021060171,Callophyllis laciniata,-9.740788,51.460563,WGS84,100,Galley Cove,"Robert Wilkes, EPA",Robert Wilkes,False,False
3,2115.0,12/5/2009,12/5/2009,D,12/5/2009,NHMSYS0021060119,Catenella caespitosa,-9.740788,51.460563,WGS84,100,Galley Cove,"Robert Wilkes, EPA",Robert Wilkes,False,False
4,2116.0,12/5/2009,12/5/2009,D,12/5/2009,NHMSYS0021059800,Ceramium shuttleworthianum,-9.740788,51.460563,WGS84,100,Galley Cove,"Robert Wilkes, EPA",Robert Wilkes,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10809,2532.0,16/09/2009,16/09/2009,D,16/09/2009,NHMSYS0021060033,Plumaria plumosa,-7.509351,55.264523,WGS84,100,Lenan Head,"Robert Wilkes, EPA",Robert Wilkes,False,False
10810,2533.0,16/09/2009,16/09/2009,D,16/09/2009,NHMSYS0021060205,Polyides rotunda,-7.509351,55.264523,WGS84,100,Lenan Head,"Robert Wilkes, EPA",Robert Wilkes,False,False
10811,2536.0,16/09/2009,16/09/2009,D,16/09/2009,NHMSYS0021060280,Rhodothamniella floridula,-7.509351,55.264523,WGS84,100,Lenan Head,"Robert Wilkes, EPA",Robert Wilkes,False,False
10812,2537.0,16/09/2009,16/09/2009,D,16/09/2009,NHMSYS0000567730,Scytosiphon lomentaria nom. cons.,-7.509351,55.264523,WGS84,100,Lenan Head,"Robert Wilkes, EPA",Robert Wilkes,False,False
10813,2538.0,16/09/2009,16/09/2009,D,16/09/2009,NHMSYS0021381089,Ulva fenestrata,-7.509351,55.264523,WGS84,100,Lenan Head,"Robert Wilkes, EPA",Robert Wilkes,False,False